on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: set-time
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Update
      run: |
        cd elecv2p
        bash elecv2p.sh>lxk0301_cdn_elecv2p.json
		
    - name: commit
      run: |
        cd elecv2p
        git add lxk0301_cdn_elecv2p.json
        git commit -m "update" -a
		
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}